language: python
python:
  - "3.9"

before_script:
  - pip install -r requirements.txt

branches:
  only:
    - master

env: DJANGO_SETTINGS_MODULE="elococo.settings"

dist: xenial

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
