sudo: false
language: python
python:
  - "3.9"

env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest

before_script:
  - pip install -r requirements.txt

branches:
  only:
    - master

env: DJANGO_SETTINGS_MODULE="elococo.settings"

dist: xenial

script:
  - python manage.py makemigrations sale catalogue
  - python manage.py migrate
  - python manage.py test
